var hash=window.location.hash.substring(1);function startstopwatch(intmslapsed){var fiveSeconds=new Date().getTime()-intmslapsed;$('#clock').countdown(fiveSeconds,{elapse:true}).on('update.countdown',function(event){var $this=$(this);if(event.elapsed){$this.html(event.strftime('<i class="fa fa-spin fa-spinner"></i> <span><font color="black">%H hr %M min %S secs ago </font></span>'));}else{$this.html(event.strftime('<span>%H:%M:%S</span>'));}});}
function funcOnclick(newType,elemid){if(newType=='Text'){document.getElementById('chunk_'+elemid).innerHTML=hex2asc(document.getElementById('chunk_ori_'+elemid).innerHTML);}else if(newType=='Num'){document.getElementById('chunk_'+elemid).innerHTML=hex2dec(document.getElementById('chunk_ori_'+elemid).innerHTML);}else if(newType=='Addr'){document.getElementById('chunk_'+elemid).innerHTML=hex2addr(document.getElementById('chunk_ori_'+elemid).innerHTML);}else if(newType=='Hex'){document.getElementById('chunk_'+elemid).innerHTML=document.getElementById('chunk_ori_'+elemid).innerHTML;}
document.getElementById('convert_button_'+elemid).innerHTML=newType;}
var gotNoteChange=true;$(document).ready(function(){$('#txtPrivateNoteArea').change(function(event){if(gotNoteChange==true){updateNote();};gotNoteChange=true;});if(hash!=''){activaTab(hash);}});$('#txtPrivateNoteArea').keypress(function(event){if(event.keyCode==13){event.preventDefault();updateNote();gotNoteChange=false;}});function updateNote(){var txhash=window.location.pathname.substring(4);var privnote=document.getElementById("txtPrivateNoteArea").value;$.ajax({type:'Get',url:'/updateHandler',data:{opr:'updatenotetx',tx:txhash,txt:privnote},success:function(res){if(res==0){$("#privatenotetip").html("<font color='#11A340'><i class='fa fa-check'></i> Your private Note has been successfully updated.</font>");}else if(res==1){$("#privatenotetip").html("<font color='gray'><i class='fa fa-exclamation-circle'></i> Sorry but to update your private note, You have to be <font color='#48B8EE'><a href='https://etherscan.io/login?returntx="+txhash+"'><b>Logged In</b></a></font> first.</font>");}else if(res==2){$("#privatenotetip").html("<font color='red'><i class='fa fa-exclamation-triangle'></i> Unable to update private note. General exception error occurred.</font>");}else if(res==3){$("#privatenotetip").html("<font color='gray'><i class='fa fa-exclamation-circle'></i> The private note was successfully removed.</font>");}else if(res==4){$("#privatenotetip").html("<font color='red'><i class='fa fa-exclamation-triangle'></i> Unable to remove private note. General exception error occurred.</font>");}else if(res==5){$("#privatenotetip").html("<font color='red'><i class='fa fa-exclamation-triangle'></i> Sorry, we were unable to add a new private Note. You have exceeded the maximum allowed quota (500 notes) per user.</font>");}},error:function(XMLHttpRequest,textStatus,errorThrown){console.log(textStatus);}});};function activaTab(tab){if(tab.indexOf('internal')>=0){tab='internal';}else if(tab.indexOf('overview')>=0){tab='overview';}else if(tab.indexOf('comment')>=0){tab='comments';loaddisqus();};;$('.nav-tabs a[href="#'+tab+'"]').tab('show');};var tmpval;var currentmode='hex';var orival="";if(document.getElementById("inputdata")!=null){orival=document.getElementById("inputdata").innerHTML;}
var rawinput="";if(document.getElementById("rawinput")!=null){rawinput=document.getElementById("rawinput").innerHTML;}
function convertstr(strval){if(currentmode=='hex'){if(rawinput!=""){tmpval=hex2asc(rawinput);}else{tmpval=hex2asc(strval);}
document.getElementById('inputdata').innerHTML=tmpval;document.getElementById('ContentPlaceHolder1_btnconvert222').innerHTML='Switch Back';currentmode='asc';}else{tmpval=asc2hex(strval);document.getElementById('inputdata').innerHTML=orival;document.getElementById('ContentPlaceHolder1_btnconvert222').innerHTML='Convert To Ascii';currentmode='hex'}}
function updatehash(strhash){if(strhash==''){history.replaceState("",document.title,window.location.pathname);}else{var baseUrl=window.location.href.split('#')[0];history.replaceState("",document.title,baseUrl+'#'+strhash);}}
function asc2hex(pStr){tempstr='';for(a=0;a<pStr.length;a=a+1){tempstr=tempstr+pStr.charCodeAt(a).toString(16);}
return tempstr;}
function hex2asc(pStr){tempstr='';for(b=0;b<pStr.length;b=b+2){tempstr=tempstr+String.fromCharCode(parseInt(pStr.substr(b,2),16));}
return tempstr;}
function hex2dec(pStr){var web3=new Web3();tempstr=new web3.BigNumber(pStr,16)
return tempstr.toString();}
function hex2addr(pStr){tempstr=pStr.substr(pStr.length-40)
return "<a href='https://etherscan.io/address/0x"+tempstr+"'>"+"0x"+tempstr+"</a>";}
function hexpad(instr){if(instr.length%2)return '0'+instr;else return instr;}
var analyticsloaded=false;function loadanalytics(){if(analyticsloaded==false){var dsq=document.createElement('script');dsq.type='text/javascript';dsq.async=true;dsq.src='//'+disqus_shortname+'.disqus.com/embed.js';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(dsq);disqusloaded=true;}
updatehash('comments');}
var interval;var loopcounter=1;if(startTxPendingCheck){var div=document.getElementById('spinnerwait');div.style.display='block';interval=setTimeout(checkForConfirmedTx,2000);function checkForConfirmedTx(){if(loopcounter<45){$.ajax({url:"/api?module=localchk&action=txexist&txhash="+txHash,type:"GET",success:function(data){if(data.result=="True"){window.location.href="https://etherscan.io/tx/"+txHash;}},dataType:"json"})
loopcounter=loopcounter+1;interval=setTimeout(checkForConfirmedTx,20000);}else{stopInterval();}}
function stopInterval(){console.log("stopInterval called");var div=document.getElementById('spinnerwait');div.style.display='none';clearTimeout(interval);}
function startInterval(){console.log("startInterval called");clearTimeout(interval);var div=document.getElementById('spinnerwait');div.style.display='block';interval=setTimeout(checkForConfirmedTx,5000);}}
var blnIsCurrentPrice=true;if(document.getElementById("pricebutton")!=null){var currentPrice=document.getElementById('pricebutton').innerText;$("#pricebutton").click(function(){if(blnIsCurrentPrice==true){document.getElementById('pricebutton').innerText=LitOldPrice;$('#pricebutton').attr('data-original-title','Estimated Value at Time of Txn');$('#pricebutton').tooltip();$(this).mouseover();blnIsCurrentPrice=false;}else{document.getElementById('pricebutton').innerText=currentPrice;$('#pricebutton').attr('data-original-title','Current Value');$('#pricebutton').tooltip();$(this).mouseover();blnIsCurrentPrice=true;}});}
var disqusloaded=false;function loaddisqus(){if(disqusloaded==false){var dsq=document.createElement('script');dsq.type='text/javascript';dsq.async=true;dsq.src='//'+disqus_shortname+'.disqus.com/embed.js';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(dsq);disqusloaded=true;}
updatehash('comments');}
function Count(text){var maxlength=100;var object=document.getElementById(text.id)
if(object.value.length>maxlength){object.focus();object.value=text.value.substring(0,maxlength);object.scrollTop=object.scrollHeight;return false;}
return true;}